# Generated by Django 4.1 on 2022-10-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=1000)),
                ('banner', models.ImageField(default='', upload_to='../images/banners/')),
            ],
        ),
    ]
