# Generated by Django 4.1 on 2022-10-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='banner',
            field=models.ImageField(default='', upload_to='images/ads/'),
        ),
    ]
