# Generated by Django 4.1 on 2022-11-03 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0023_alter_products_options_alter_showproductas_options'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(default=0)),
                ('order_code', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('prize', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('delivery_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.deliveryaddress')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'verbose_name': 'Products Ordered',
                'verbose_name_plural': 'Products Ordered',
            },
        ),
    ]
