# Generated by Django 4.1 on 2022-08-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.CharField(default='HAONAONX', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
