# Generated by Django 4.1 on 2022-08-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='ref',
            field=models.CharField(default='TCOIY24F', max_length=10),
        ),
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
