# Generated by Django 4.1 on 2022-08-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_subcategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='category_id',
            new_name='category',
        ),
    ]
