# Generated by Django 4.1 on 2022-09-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_category_id_subcategories_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='category',
            new_name='category_id',
        ),
    ]
