# Generated by Django 4.1 on 2022-09-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_products_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="img_1",
            field=models.ImageField(default="", upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="products",
            name="img_2",
            field=models.ImageField(blank=True, default="", upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="products",
            name="img_3",
            field=models.ImageField(blank=True, default="", upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="subcategories", name="category_id", field=models.IntegerField(),
        ),
    ]
