# Generated by Django 4.1 on 2022-09-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_products_img_1_alter_products_img_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products", name="category_id", field=models.IntegerField(),
        ),
    ]
