# Generated by Django 4.1 on 2022-09-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_products_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='show_for',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='vendor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
