# Generated by Django 4.1 on 2022-10-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_products_category_id_alter_products_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowProductAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='show_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.showproductas'),
        ),
    ]
