# Generated by Django 4.1 on 2022-10-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_status_stock_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.status'),
        ),
    ]
