# Generated by Django 4.1 on 2022-10-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_products_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='ProductStatus',
        ),
    ]
