# Generated by Django 4.1 on 2022-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_status_productstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img_1',
            field=models.ImageField(default='', upload_to='../images/products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_2',
            field=models.ImageField(blank=True, default='', upload_to='../images/products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_3',
            field=models.ImageField(blank=True, default='', upload_to='../images/products/'),
        ),
    ]
