# Generated by Django 4.1 on 2022-10-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_products_img_1_alter_products_img_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img_1',
            field=models.ImageField(default='', upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_2',
            field=models.ImageField(blank=True, default='', upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_3',
            field=models.ImageField(blank=True, default='', upload_to='images/products/'),
        ),
    ]
