# Generated by Django 4.1 on 2022-10-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_products_img_1_alter_products_img_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Categories'},
        ),
    ]
