# Generated by Django 4.1 on 2022-10-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_categories_options_alter_productstatus_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
