# Generated by Django 4.1 on 2022-11-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_products_options_alter_showproductas_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=500)),
                ('manager_name', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('ghana_card', models.FileField(default='', upload_to='documents/vendors/ghanacard')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.vendors'),
        ),
    ]
