# Generated by Django 4.1 on 2022-11-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_vendors_alter_products_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='vendor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.vendors'),
        ),
    ]
