# Generated by Django 4.1 on 2022-11-21 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_products_vendor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategories')),
            ],
            options={
                'verbose_name': 'Sub Sub Category',
                'verbose_name_plural': 'Sub Sub Categories',
            },
        ),
    ]
