# Generated by Django 4.1 on 2022-11-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_subsubcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img_4',
            field=models.ImageField(blank=True, default='', upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='img_5',
            field=models.ImageField(blank=True, default='', upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='img_6',
            field=models.ImageField(blank=True, default='', upload_to='images/products/'),
        ),
    ]
