# Generated by Django 4.1 on 2022-11-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_products_sub_sub_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubcategories',
            name='ref_code',
            field=models.CharField(default='TMAL7YH3', max_length=500),
        ),
    ]
