# Generated by Django 4.1 on 2022-12-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_subsubcategories_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubcategories',
            name='ref_code',
            field=models.CharField(default='N1BNHP25', max_length=500),
        ),
    ]
