# Generated by Django 4.1 on 2022-12-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_subsubcategories_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img_1',
            field=models.ImageField(default='', upload_to='https://storage.googleapis.com/sassty-5b85e.appspot.com/images/'),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='ref_code',
            field=models.CharField(default='ASU73TFM', max_length=500),
        ),
    ]
