# Generated by Django 4.1 on 2022-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_products_img_1_alter_subsubcategories_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img_1',
            field=models.ImageField(default='', upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='subsubcategories',
            name='ref_code',
            field=models.CharField(default='W253R7MJ', max_length=500),
        ),
    ]
